
    $(document).ready(function(){
        $('#show').click(function(){
         $('#hide1').slideToggle('slow')         
        })
    })
    $(document).ready(function(){
        $('#show2').click(function(){
         $('#hide2').slideToggle('slow')         
        })
    })
    $(document).ready(function(){
        $('#show3').click(function(){
         $('#hide3').slideToggle('slow')         
        })
    })
    $(document).ready(function(){
        $('#show4').click(function(){
         $('#hide4').slideToggle('slow')         
        })
    })
    $(document).ready(function(){
        $('#show5').click(function(){
         $('#hide5').slideToggle('slow')         
        })
    })
    $(document).ready(function(){
        $('#show6').click(function(){
         $('#hide6').slideToggle('slow')         
        })
    })